# Generated by Django 5.2.13 on 2026-05-09 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('craft', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('image', models.ImageField(upload_to='artisans/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='product',
            name='artisan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.artisan'),
        ),
    ]
