# Generated by Django 5.2.13 on 2026-05-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_artisan_alter_product_price_product_artisan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('craft', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('image', models.ImageField(upload_to='applications/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
