# Generated by Django 5.2.13 on 2026-05-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_artisan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanapplication',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
